# Generated by Django 5.2.8 on 2025-12-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("status", models.CharField(max_length=10)),
            ],
        ),
    ]
